Code Review #2
2006-cpu/codalorians pull request #66
Opened 2020-11-24 02:51 UTC by kati-unu

2020-11-24 05:11 UTC, rabdulr requested changes
Please make changes regarding code that's not being utilized.
Makes for Product Route

2020-11-24 05:11 UTC, rabdulr commented on src/components/SingleOrder.js
> +    const fetchOrders = () => {
Have a specific route for orders that looks ups by person rather than filtering through all orders on the front end.

2020-11-30 05:13 UTC, Zezlita commented on db/init_db.js
> +        imageURL VARCHAR(255) DEFAULT 'https://icon-library.com/images/no-image-available-icon/no-image-available-icon-8.jpg',
this was updated with: https://icon-library.com/images/no-image-available-icon/no-image-available-icon-8.jpg

2020-11-30 05:40 UTC, Zezlita commented on db/users.js
> +        if (isMatch === true) {
fixed this to remove argument

2020-11-30 05:41 UTC, Zezlita commented on db/users.js
> +        }else if ([isMatch === false]) {
fixed this with (!isMatch)

2020-11-30 06:49 UTC, Zezlita commented on routes/index.js
> +const {JWT_SECRET} = process.env
added "JWT_SECRET = 'notSoSecret';"

2020-11-30 07:08 UTC, Zezlita commented on routes/users.js
> +usersRouter.use((req, res, next) => {
moved this up to right below const to line 15

2020-11-30 07:08 UTC, Zezlita commented on routes/users.js
> +usersRouter.post('/register', async (req, res, next) => {
WIP

2020-11-30 07:09 UTC, Zezlita commented on routes/users.js
> +usersRouter.post('/login', async (req, res, next) => {
- fixed login by adding JWT to heroku
- added "delete user.password" to getUserById function

2020-11-30 07:10 UTC, Zezlita commented on routes/users.js
> +        // if(req.user.id === userId){
will remove at submission

2020-11-30 07:10 UTC, Zezlita commented on src/components/App.js
> +  /* We'll persist login here */
will remove at submission

2020-11-30 07:10 UTC, Zezlita commented on src/components/App.js
> +  /* We'll persist login here */
will remove at submission

2020-11-30 07:17 UTC, Zezlita commented on src/components/Board.js
> +        async function fetchProducts(){
I tried fixing this, but I keep breaking it as I move these out.. I think I will need any other pair of eyes to help with this

2020-11-30 07:18 UTC, Zezlita commented on src/components/Board.js
> +{initialRender.map((product) => {
Looks like this was updated?

2020-11-30 07:19 UTC, Zezlita commented on src/components/Login.js
> +            const response = await axios.post(`/api/users/login`, {username, password})
destructured to:
const {data} = await axios.post(`/api/users/login`, {username, password})

2020-11-30 07:20 UTC, Zezlita commented on src/components/Login.js
> +
WIP

2020-11-30 07:21 UTC, Zezlita commented on src/components/Login.js
> +            if(user && user,username) {
fixed

2020-11-30 07:21 UTC, Zezlita commented on src/components/Login.js
> +                console.log("We have successfully logged in!!!");
we'll need to create this

2020-11-30 07:23 UTC, Zezlita commented on src/components/ProductCard.js
> +import {Link, useParams} from 'react-router-dom';
not sure yet, but we'll remove if it's not being used at submission

2020-11-30 07:24 UTC, Zezlita commented on src/components/SelectedProductPg.js
> +        async function fetchProducts(){
I tried moving it out but I kept getting errors, I would need another pair of eyes to help with this..

2020-11-30 07:51 UTC, Zezlita commented on src/components/SingleOrder.js
> +    const fetchOrders = () => {
WIP!

2020-11-30 07:51 UTC, Zezlita commented on db/order_products.js
> +const {client} = require("./index")
will do!

2020-11-30 07:52 UTC, Zezlita commented on routes/orders.js
> +        // const { userId } = req.params;
we'll be sure to remove before final submission!

2020-11-30 07:52 UTC, Zezlita commented on routes/orders.js
> +            // return newOrder;
we'll be sure to remove before final submission

2020-11-30 07:56 UTC, Zezlita commented
Left comments to those that were fixed, still need:
- register (frontend)
- useEffect
- redirect after sign in
- error messages
- fetch order by user

2020-12-01 03:49 UTC, rabdulr commented on db/init_db.js
> +        imageURL VARCHAR(255) DEFAULT NULL,
Awesome!

2020-12-01 03:54 UTC, rabdulr commented on routes/order_products.js
> +const { getOrderById } = require('../db/orders');
Look into importing/exporting with index

2020-12-01 03:55 UTC, rabdulr commented on routes/order_products.js
> +        // const orderProduct = await getOrderProductById(orderProductId);
Please remove comment from production.

2020-12-01 03:58 UTC, rabdulr commented on routes/users.js
> +usersRouter.get('/me', /* requireUser,  */async(req, res, next) => {
If you're not using function, please remove

2020-12-03 03:02 UTC, rabdulr requested changes
Please fix user login.

2020-12-03 03:39 UTC, rabdulr approved these changes
Changes look good. Please continue with adding functionality like creating and adding products to a cart.

2020-12-03 03:45 UTC, merged