Orders backend orders api routes #55
2006-cpu/codalorians pull request #73
Opened 2020-11-29 08:32 UTC by Zezlita

#55 
Created patch & delete API routes

2020-11-29 16:35 UTC, tpadilla10117 commented on routes/orders.js
> +    ordersRouter.delete('/:orders/:orderId', requireUser, async (req, res, next) => {
Quick fix: '/orders/:orderId'

2020-11-29 16:37 UTC, tpadilla10117 requested changes
Looks good! One small fix in the comments.  We'll see if the others spot anything else!  Also need to test these ASAP, unless you did already!

2020-11-29 20:03 UTC, Zezlita commented on routes/orders.js
> +    ordersRouter.delete('/:orders/:orderId', requireUser, async (req, res, next) => {
Thanks Trin! This is fixed!

2020-11-30 22:11 UTC, tpadilla10117 approved these changes

2020-11-30 23:38 UTC, kati-unu requested changes

2020-11-30 23:38 UTC, kati-unu commented on routes/orders.js
> +            if(order && order.userId !== req.userId){
req.userId works? vs req.user.id?

2020-11-30 23:38 UTC, kati-unu commented on routes/orders.js
> +    ordersRouter.patch('/orders:orderId', requireUser, async (req, res, next) => {
remove /orders for both routes

2020-11-30 23:38 UTC, kati-unu commented on routes/orders.js
> +    ordersRouter.patch('/orders:orderId', requireUser, async (req, res, next) => {
and add route to the index.js

2020-12-01 03:26 UTC, Zezlita commented on routes/orders.js
> +            if(order && order.userId !== req.userId){
adjusted to req.user.id

2020-12-01 03:26 UTC, Zezlita commented on routes/orders.js
> +    ordersRouter.patch('/orders:orderId', requireUser, async (req, res, next) => {
updated!

2020-12-05 04:49 UTC, kati-unu approved these changes

2020-12-05 04:50 UTC, merged